### PR TITLE
Update to embassy-sync 0.6

### PR DESCRIPTION
**Pull request by zeenix**

### CODE REVIEW

**Comment by jamesmunns** [comment]
I'm okay with this, but I'm going to hold off merging it until I'm ready for the 0.6 release, as this is a breaking change. I don't expect 0.6 to be far off.

**Review by jamesmunns — APPROVED** [review]
Approved pending next breaking release

**Comment by zeenix** [comment]
Just FYI, rebased on top of current main to keep things in sync.

**Comment by jamesmunns** [comment]
@zeenix this is failing CI, I'd like to do a release of this, any chance you can check out what's wrong?

**Comment by jamesmunns** [comment]
Issue was the example project also needed to be updated

**Pull request merged**
